#!/usr/bin/env python3
"""Generate conservative TH10 progress directly from the ledgers."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config"
OUTPUT = ROOT / "docs" / "PROGRESS.md"
SVG = ROOT / "resources" / "progress.svg"


def rows(name: str) -> list[dict[str, str]]:
    with (CONFIG / name).open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def parse_address(value: str) -> int:
    """Parse a ledger address without depending on its hex formatting."""
    return int(value, 0)


def measures() -> dict[str, int]:
    functions = rows("functions.csv")
    origins = {
        parse_address(row["address"]): row
        for row in rows("function-origins.csv")
    }
    mappings = rows("reccmp-functions.csv")
    matches = rows("matches.csv")
    implemented = []
    with (CONFIG / "implemented.csv").open(newline="", encoding="utf-8") as stream:
        implemented = [row[0] for row in csv.reader(stream) if row and row[0]]
    def disposition(row: dict[str, str]) -> str:
        return origins[parse_address(row["address"])]["disposition"]

    authored = [row for row in functions if disposition(row) == "authored"]
    excluded = [row for row in functions if disposition(row) == "exclude"]
    exact_bytes = sum(int(row["size"], 0) for row in matches)
    authored_bytes = sum(int(row["size"], 0) for row in authored)
    reviewed = len(authored) + len(excluded)
    mapped_authored = sum(
        disposition(row) == "authored" for row in mappings
    )
    mapped_review = sum(
        disposition(row) == "review" for row in mappings
    )
    mapped_excluded = sum(
        disposition(row) == "exclude" for row in mappings
    )
    return {
        "functions": len(functions),
        "reviewed": reviewed,
        "pending": len(functions) - reviewed,
        "authored": len(authored),
        "authored_bytes": authored_bytes,
        "excluded": len(excluded),
        "implemented": len(implemented),
        "mapped_authored": mapped_authored,
        "mapped_review": mapped_review,
        "mapped_excluded": mapped_excluded,
        "authored_exact_backlog": mapped_authored - len(matches),
        "matches": len(matches),
        "exact_bytes": exact_bytes,
    }


def render_markdown(values: dict[str, int]) -> str:
    return f"""# TH10 reconstruction progress

Generated by `python3 scripts/progress.py`. Ghidra candidates are provisional;
their boundaries and origins must be reviewed independently.

| Measure | Count |
| --- | ---: |
| Tracked 1.00a function candidates | {values['functions']:,} |
| Origin/boundary review pending | {values['pending']:,} |
| Confirmed authored functions | {values['authored']:,} |
| Confirmed authored code bytes | {values['authored_bytes']:,} |
| Classified exclusions | {values['excluded']:,} |
| Source-present mappings | {values['implemented']:,} |
| Source-present with authored origin | {values['mapped_authored']:,} |
| Source-present origin review pending | {values['mapped_review']:,} |
| Authored source-present exact backlog | {values['authored_exact_backlog']:,} |
| Canonical exact functions | {values['matches']:,} |
| Canonical exact authored bytes | {values['exact_bytes']:,} |

While review remains pending, the authored exact denominator is unknown. A
mapped name, maintained source, successful compilation, or Ghidra similarity does
not contribute to the exact totals.
"""


def render_svg(values: dict[str, int]) -> str:
    total, reviewed = values["functions"], values["reviewed"]
    review_pct = 100 * reviewed / total if total else 0.0
    review_width = 512 * review_pct / 100
    if values["pending"]:
        exact_label = "denominator pending"
        exact_width = 0.0
        exact_detail = f"{values['matches']:,} exact functions · {values['exact_bytes']:,} exact bytes"
        aria_exact = "authored exact denominator pending"
    else:
        exact_pct = 100 * values["exact_bytes"] / values["authored_bytes"] if values["authored_bytes"] else 0.0
        exact_label = f"{exact_pct:.2f}%"
        exact_width = 512 * exact_pct / 100
        exact_detail = f"{values['matches']:,} / {values['authored']:,} functions · {values['exact_bytes']:,} / {values['authored_bytes']:,} bytes"
        aria_exact = f"authored {exact_pct:.2f}% exact bytes"
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="560" height="176" role="img" aria-label="TH10 reconstruction progress: {aria_exact}, origin review {review_pct:.2f}%">
  <rect width="560" height="176" rx="8" fill="#1f2335"/>
  <text x="24" y="28" fill="#f4f4f5" font-family="sans-serif" font-size="16" font-weight="600">TH10 reconstruction progress</text>
  <text x="24" y="52" fill="#f4f4f5" font-family="sans-serif" font-size="13" font-weight="600">Authored exact</text>
  <text x="536" y="52" fill="#f4f4f5" text-anchor="end" font-family="monospace" font-size="13">{exact_label}</text>
  <rect x="24" y="60" width="512" height="12" rx="6" fill="#3b4058"/>
  <rect x="24" y="60" width="{exact_width:.2f}" height="12" rx="6" fill="#9b6de3"/>
  <text x="24" y="89" fill="#c8cad2" font-family="sans-serif" font-size="12">{exact_detail}</text>
  <text x="24" y="116" fill="#f4f4f5" font-family="sans-serif" font-size="13" font-weight="600">Origin/boundary reviewed</text>
  <text x="536" y="116" fill="#f4f4f5" text-anchor="end" font-family="monospace" font-size="13">{review_pct:.2f}%</text>
  <rect x="24" y="124" width="512" height="12" rx="6" fill="#3b4058"/>
  <rect x="24" y="124" width="{review_width:.2f}" height="12" rx="6" fill="#9b6de3"/>
  <text x="24" y="153" fill="#c8cad2" font-family="sans-serif" font-size="12">{reviewed:,} / {total:,} candidates · {values['pending']:,} pending</text>
</svg>
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    values = measures()
    markdown, svg = render_markdown(values), render_svg(values)
    if args.check:
        stale = []
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != markdown:
            stale.append(str(OUTPUT.relative_to(ROOT)))
        if not SVG.exists() or SVG.read_text(encoding="utf-8") != svg:
            stale.append(str(SVG.relative_to(ROOT)))
        if stale:
            print(f"error: stale generated progress: {', '.join(stale)}")
            return 1
        print("progress artifacts are current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    SVG.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(markdown, encoding="utf-8")
    SVG.write_text(svg, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} and {SVG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
