#!/usr/bin/env python3
"""Generate conservative TH10 progress directly from the ledgers."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config"
OUTPUT = ROOT / "docs" / "PROGRESS.md"
SVG = ROOT / "resources" / "progress.svg"


def rows(name: str) -> list[dict[str, str]]:
    with (CONFIG / name).open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def parse_address(value: str) -> int:
    """Parse a ledger address without depending on its hex formatting."""
    return int(value, 0)


def measures() -> dict[str, int]:
    functions = rows("functions.csv")
    origins = {
        parse_address(row["address"]): row
        for row in rows("function-origins.csv")
    }
    boundaries = {
        parse_address(row["address"]): row
        for row in rows("function-boundaries.csv")
    }
    mappings = rows("reccmp-functions.csv")
    matches = rows("matches.csv")
    implemented = []
    with (CONFIG / "implemented.csv").open(newline="", encoding="utf-8") as stream:
        implemented = [row[0] for row in csv.reader(stream) if row and row[0]]
    def disposition(row: dict[str, str]) -> str:
        return origins[parse_address(row["address"])]["disposition"]

    authored = [row for row in functions if disposition(row) == "authored"]
    excluded = [row for row in functions if disposition(row) == "exclude"]
    indeterminate = [row for row in functions if disposition(row) == "indeterminate"]
    exact_bytes = sum(int(row["size"], 0) for row in matches)
    authored_exact = [row for row in matches if disposition(row) == "authored"]
    authored_exact_bytes = sum(int(row["size"], 0) for row in authored_exact)
    authored_bytes = sum(int(row["size"], 0) for row in authored)
    origin_reviewed = len(authored) + len(excluded) + len(indeterminate)
    boundary_reviewed = sum(
        boundaries[parse_address(row["address"])]["state"] == "reviewed"
        for row in functions
    )
    boundary_provisional = sum(
        boundaries[parse_address(row["address"])]["state"] == "provisional"
        for row in functions
    )
    boundary_needs_review = sum(
        boundaries[parse_address(row["address"])]["state"] == "needs_review"
        for row in functions
    )
    mapped_authored = sum(
        disposition(row) == "authored" for row in mappings
    )
    mapped_review = sum(
        disposition(row) == "review" for row in mappings
    )
    mapped_excluded = sum(
        disposition(row) == "exclude" for row in mappings
    )
    mapped_indeterminate = sum(
        disposition(row) == "indeterminate" for row in mappings
    )
    review_completed = sum(
        disposition(row) in ("authored", "exclude", "indeterminate") and
        boundaries[parse_address(row["address"])]["state"] == "reviewed"
        for row in functions
    )
    return {
        "functions": len(functions),
        "origin_reviewed": origin_reviewed,
        "origin_pending": len(functions) - origin_reviewed,
        "review_completed": review_completed,
        "review_pending": len(functions) - review_completed,
        "boundary_reviewed": boundary_reviewed,
        "boundary_provisional": boundary_provisional,
        "boundary_needs_review": boundary_needs_review,
        "boundary_pending": len(functions) - boundary_reviewed,
        "authored": len(authored),
        "authored_bytes": authored_bytes,
        "excluded": len(excluded),
        "indeterminate": len(indeterminate),
        "implemented": len(implemented),
        "mapped_authored": mapped_authored,
        "mapped_review": mapped_review,
        "mapped_excluded": mapped_excluded,
        "mapped_indeterminate": mapped_indeterminate,
        "authored_exact_backlog": mapped_authored - len(authored_exact),
        "matches": len(matches),
        "exact_bytes": exact_bytes,
        "authored_matches": len(authored_exact),
        "authored_exact_bytes": authored_exact_bytes,
    }


def render_markdown(values: dict[str, int]) -> str:
    return f"""# TH10 reconstruction progress

Generated by `scripts/repo-python scripts/progress.py`. The initial Ghidra
inventory is provisional; reviewed boundary and origin states are counted below.

| Measure | Count |
| --- | ---: |
| Tracked 1.00a function candidates | {values['functions']:,} |
| Boundary reviewed | {values['boundary_reviewed']:,} |
| Boundary provisional | {values['boundary_provisional']:,} |
| Boundary needs focused review | {values['boundary_needs_review']:,} |
| Origin review pending | {values['origin_pending']:,} |
| Confirmed authored functions | {values['authored']:,} |
| Confirmed authored code bytes | {values['authored_bytes']:,} |
| Classified exclusions | {values['excluded']:,} |
| Reviewed, origin indeterminate | {values['indeterminate']:,} |
| Source-present mappings | {values['implemented']:,} |
| Source-present with authored origin | {values['mapped_authored']:,} |
| Source-present origin review pending | {values['mapped_review']:,} |
| Source-present origin indeterminate | {values['mapped_indeterminate']:,} |
| Authored source-present exact backlog | {values['authored_exact_backlog']:,} |
| Canonical exact functions | {values['matches']:,} |
| Canonical exact codegen bytes | {values['exact_bytes']:,} |
| Canonical exact functions with authored origin | {values['authored_matches']:,} |
| Canonical exact authored bytes | {values['authored_exact_bytes']:,} |

The tracked-candidate denominator remains provisional because unresolved `.text`
gaps can contain code, data, thunks, tables, and padding. While origin review,
indeterminate attribution, or inventory closure remain pending, the authored
exact denominator is unknown. A mapped name, maintained source, successful
compilation, or Ghidra similarity
does not contribute to the exact totals.
"""


def render_svg(values: dict[str, int]) -> str:
    total = values["functions"]
    reviewed = values["review_completed"]
    review_pct = 100 * reviewed / total if total else 0.0
    review_width = 512 * review_pct / 100
    if values["review_pending"] or values["indeterminate"]:
        exact_label = "denominator pending"
        exact_width = 0.0
        exact_detail = (
            f"{values['authored_matches']:,} authored / {values['matches']:,} exact · "
            f"{values['exact_bytes']:,} codegen bytes"
        )
        aria_exact = "authored exact denominator pending"
    else:
        exact_pct = (
            100 * values["authored_exact_bytes"] / values["authored_bytes"]
            if values["authored_bytes"] else 0.0
        )
        exact_label = f"{exact_pct:.2f}%"
        exact_width = 512 * exact_pct / 100
        exact_detail = (
            f"{values['authored_matches']:,} / {values['authored']:,} authored · "
            f"{values['authored_exact_bytes']:,} / {values['authored_bytes']:,} bytes"
        )
        aria_exact = f"authored {exact_pct:.2f}% exact bytes"
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="560" height="176" role="img" aria-label="TH10 reconstruction progress: {aria_exact}, origin and boundary review {review_pct:.2f}%">
  <rect width="560" height="176" rx="8" fill="#1f2335"/>
  <text x="24" y="28" fill="#f4f4f5" font-family="sans-serif" font-size="16" font-weight="600">TH10 reconstruction progress</text>
  <text x="24" y="52" fill="#f4f4f5" font-family="sans-serif" font-size="13" font-weight="600">Authored exact</text>
  <text x="536" y="52" fill="#f4f4f5" text-anchor="end" font-family="monospace" font-size="13">{exact_label}</text>
  <rect x="24" y="60" width="512" height="12" rx="6" fill="#3b4058"/>
  <rect x="24" y="60" width="{exact_width:.2f}" height="12" rx="6" fill="#9b6de3"/>
  <text x="24" y="89" fill="#c8cad2" font-family="sans-serif" font-size="12">{exact_detail}</text>
  <text x="24" y="116" fill="#f4f4f5" font-family="sans-serif" font-size="13" font-weight="600">Origin/boundary reviewed</text>
  <text x="536" y="116" fill="#f4f4f5" text-anchor="end" font-family="monospace" font-size="13">{review_pct:.2f}%</text>
  <rect x="24" y="124" width="512" height="12" rx="6" fill="#3b4058"/>
  <rect x="24" y="124" width="{review_width:.2f}" height="12" rx="6" fill="#9b6de3"/>
  <text x="24" y="153" fill="#c8cad2" font-family="sans-serif" font-size="12">{reviewed:,} / {total:,} candidates · {values['review_pending']:,} pending</text>
</svg>
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    values = measures()
    markdown, svg = render_markdown(values), render_svg(values)
    if args.check:
        stale = []
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != markdown:
            stale.append(str(OUTPUT.relative_to(ROOT)))
        if not SVG.exists() or SVG.read_text(encoding="utf-8") != svg:
            stale.append(str(SVG.relative_to(ROOT)))
        if stale:
            print(f"error: stale generated progress: {', '.join(stale)}")
            print("regenerate with: scripts/repo-python scripts/progress.py")
            return 1
        print("progress artifacts are current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    SVG.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(markdown, encoding="utf-8")
    SVG.write_text(svg, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} and {SVG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
